### PR TITLE
Chinese case and other tweaks

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/33)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/33)* status: 0 of 7 files reviewed, 5 unresolved discussions

___
*[`.github/workflows/release.yml` line 39 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXO8Tj32mNj7EXjI7V:-OBXO8Tj32mNj7EXjI7W:b-tnewpl) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d2183c8c508df76df1956855e4d1a31e54c2916c/.github/workflows/release.yml#L39)):*
> ```YAML
>       # find-language is a dependency of langauge-chooser-react-mui so it will have been built in the build step
>       - name: Run tests
>         run: npx nx run-many --all --target=test
> ```

Forgot to do this when I added tests to language-chooser-react-hook. In addition should we try pushing a commit with broken tests to test what happens? 
___
*[`components/language-chooser/react/language-chooser-react-mui/tsconfig.storybook.json` line 11 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXQ3Nq9oTIM8Lp9l6A:-OBXQ3Nq9oTIM8Lp9l6B:b-ifn0h7) ([raw file](https://github.com/sillsdev/EthnoLib/blob/3aa68983c12c698c7d83ab6fdfc64d7142cca692/components/language-chooser/react/language-chooser-react-mui/tsconfig.storybook.json#L11)):*
> ```JSON
>     "../../../../node_modules/@nx/react/typings/cssmodule.d.ts",
>     "../../../../node_modules/@nx/react/typings/image.d.ts"
>   ],
> ```

Not sure why these we're here. I probably didn't notice them being automatically added. I don't think they make any sense
___
*[`components/language-chooser/common/find-language/searchResultModifiers.ts` line 24 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXP0qq6JAvXnOrJzFt:-OBXP0qq6JAvXnOrJzFu:b31pmw4) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d2183c8c508df76df1956855e4d1a31e54c2916c/components/language-chooser/common/find-language/searchResultModifiers.ts#L24)):*
> ```XML
> }
> 
> export function modifyScripts(
> ```

We can use this if we decide to modify the "Han (simplified variant)" script cards for other languages
___
*[`components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts` line 159 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXPpe1AIFB46UUjPep:-OBXPpe1AIFB46UUjPeq:bfiqrdh) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d2183c8c508df76df1956855e4d1a31e54c2916c/components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts#L159)):*
> ```XML
>     if (codeMatches(script.code, selectedScript?.code)) {
>       // if the display name is our automatically set Chinese (Simplified) for zh-Hans or Chinese (Traditional) for zh-Hant,
>       // then we want to reset to the default display name for Chinese with no selected script
> ```

I did what I think makes most sense but someone should definitely try out this display name behavior and make sure it feels reasonable
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 50 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXOJKV1OEsE2FO3HB6:-OBXOJKV1OEsE2FO3HB7:b-d02ixj) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d2183c8c508df76df1956855e4d1a31e54c2916c/components/language-chooser/common/find-language/searchForLanguage.ts#L50)):*
> ```XML
>     ...baseFuseOptions,
>     ignoreLocation: true,
>     threshold: 0.3,
> ```

Broaden results to even fuzzier matches. With threshold 0.2, "uzbk" didn't pull up "uzbek". 0.3 pulls up more clearly-unrelated results, but I thought better err on that side for now

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/33)* status: 0 of 7 files reviewed, 6 unresolved discussions

___
*[`components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts` line 233 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXQI7V5PeyLvM_ZTW8:-OBXQI7V5PeyLvM_ZTW9:b-d4opbn) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d2183c8c508df76df1956855e4d1a31e54c2916c/components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts#L233)):*
> ```XML
> };
> 
> export function defaultDisplayName(language: ILanguage) {
> ```

I'm not sure what file to put this function in. It doesn't seem to belong anywhere

**Review by andrew-polk — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/33)* status: all files reviewed, 6 unresolved discussions (waiting on @nabalone)

___
*[`.github/workflows/release.yml` line 39 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/33#-OBXO8Tj32mNj7EXjI7V:-OBXUiqQB5JKYIZSczLM:b-illa9u) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d2183c8c508df76df1956855e4d1a31e54c2916c/.github/workflows/release.yml#L39)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Forgot to do this when I added tests to language-chooser-react-hook. In addition should we try pushing a commit with broken tests to test what happens?
</blockquote></details>

Sure. Sounds like fun! : )

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/33)* status: all files reviewed, 5 unresolved discussions

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
