### PR TITLE
Language chooser changes since last review

### PR DESCRIPTION
**Pull request by nabalone**
Changes since last live review/pairing session

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/2)

### CODE REVIEW

**Comment by DavidLRowe** [comment]
Do you have a short video of a demo of the language chooser?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/2)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[`components/language-picker/README.md` line 11 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/2#-O4fzW9z5z491jkGj2mk:-O4fzW9z5z491jkGj2ml:bh9d99e) ([raw file](https://github.com/sillsdev/EthnoLib/blob/6029ff6740caffb0d92f2542b0fcf5f0f7075e88/components/language-picker/README.md#L11)):*
> ```Markdown
> - Simplifies the English and French cards to remove the regions lists and most alternative names
> - Remove certain entries from langtags.json that don' represent specific extant human languages, such as zxx (no linguistic content) or ang (old english)
> - filters out Braille from the script options, as well as script codes that do not refer to specific relevant scripts
> ```

A few tweaks:
```
`language-picker/common/find-language` contains the logic for fuzzy-searching for languages, suitable to be published on its own and usable by various frontends. The database of languages is based on [langtags.json](https://github.com/silnrsi/langtags). Also has various methods for modifying the search results to handle special cases (e.g. sign languages and very common languages). Currently, corner cases in the search results are adjusted as makes sense for Bloom's use cases by `defaultSearchResultModifier` which

- ensures the English result comes up on top if the user starts typing "English"
- ensures the French result comes up on top if the user starts typing "French", "Francais" or "français"
- simplifies the English and French cards to remove the regions lists and most alternative names
- removes certain entries from langtags.json that don't represent specific extant human languages, such as zxx (no linguistic content) or ang (old english)
- filters out Braille from the script options, as well as script codes that do not refer to specific relevant scripts
```
___
*[`components/language-picker/common/find-language/getShortestSufficientLangtag.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/2#-O4g-BDD6_n7JwaQoDiM:-O4g-BDD6_n7JwaQoDiN:bx9nuif) ([raw file](https://github.com/sillsdev/EthnoLib/blob/6029ff6740caffb0d92f2542b0fcf5f0f7075e88/components/language-picker/common/find-language/getShortestSufficientLangtag.ts#L3)):*
> ```XML
> import shortestTags from "./shortestTagLookups.json" assert { type: "json" };
> 
> export const shortPreferredTagLookup = new Map<string, string>();
> ```

Any reason to export this?
___
*[`components/language-picker/common/find-language/getShortestSufficientLangtag.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/2#-O4g-1oH6vskGpoitV_a:-O4g-1oH6vskGpoitV_b:bgnuu5s) ([raw file](https://github.com/sillsdev/EthnoLib/blob/6029ff6740caffb0d92f2542b0fcf5f0f7075e88/components/language-picker/common/find-language/getShortestSufficientLangtag.ts#L13)):*
> ```XML
>   return shortPreferredTagLookup.get(langtag) || langtag;
> }
> // TODO don't forget about casing
> ```

TO-DONE?
___
*[`components/language-picker/common/find-language/langtags.txt` line 1 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/2#-O4g1R3FAtAB_ddyFxLW:-O4g1R3FAtAB_ddyFxLX:b-nl5lf1) ([raw file](https://github.com/sillsdev/EthnoLib/blob/6029ff6740caffb0d92f2542b0fcf5f0f7075e88/components/language-picker/common/find-language/langtags.txt#L1)):*
> ```help
> *aa = *aa-ET = aa-Latn = aa-Latn-ET
> ```

Does this file come from the langtags repo?
We need to mention it in the readme along with langtags.json.
___
*[`components/language-picker/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx` line 38 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/2#-O4g0V4s-2M7bRAUYtzJ:-O4g0V4s-2M7bRAUYtzK:b-5o1qyj) ([raw file](https://github.com/sillsdev/EthnoLib/blob/6029ff6740caffb0d92f2542b0fcf5f0f7075e88/components/language-picker/react/language-chooser-react-mui/src/CustomizeLanguageDialog.tsx#L38)):*
> ```XML
>       };
>     })
>     .filter((region) => region.label !== "Congo");
> ```

So even this new library has a problem with Congo?
Let's add a comment here.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/2)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
