### PR TITLE
Language chooser unreviewed

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/3)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/3)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[`package.json` line 28 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lPzkpC7voFO2dzI1k:-O4lPzkpC7voFO2dzI1l:b-hqhlf1) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/package.json#L28)):*
> ```JSON
>     "@emotion/react": "^11.11.4",
>     "@emotion/styled": "^11.11.5",
>     "@mui/material": "^5.15.19"
> ```

Seems wrong for emotion and mui to be at this top level.
And the react types.
___
*[`components/language-picker/README.md` line 3 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lQWJb0aziiYyjCJfe:-O4lQWJb0aziiYyjCJff:b-ukaxra) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/README.md#L3)):*
> ```Markdown
> # Language Picker
> 
> This project was initially developed for use in Bloom Desktop.
> ```

Typically if we refer to it in prose, it is the Bloom Editor. Or it can be the repo: BloomDesktop. Maybe worth a link to the repo?
___
*[`components/language-picker/README.md` line 28 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lR353-cYodzTKM8wz:-O4lR353-cYodzTKM8x-:b-gpykxu) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/README.md#L28)):*
> ```Markdown
> First, set up Nx if you haven't done so already (see [README.md](../../README.md)).
> 
> We recommend installing nx globally, but if you haven't, you can just prefix all the commands with `npx`
> ```

Let's be consistent with capitalization of "Nx".
I suggest lowercase everywhere.
___
*[`components/language-picker/README.md` line 40 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lRNtF9NieJ41iTp0T:-O4lRNtF9NieJ41iTp0U:b-hd65jc) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/README.md#L40)):*
> ```Markdown
> ## Unit tests
> 
> Language picker uses vitest for unit testing. . To run tests, use:
> ```

Extra period.
___
*[`components/language-picker/common/find-language/package.json` line 37 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lQDJ87FsMtTG8K5ag:-O4lQDJ87FsMtTG8K5ah:bs639wk) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/common/find-language/package.json#L37)):*
> ```JSON
>   "peerDependencies": {
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2"
> ```

Why does this package need react stuff?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/3)* status: 3 of 15 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`package.json` line 28 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lPzkpC7voFO2dzI1k:-O4lShnp4Q6oOFJz6BI0:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/package.json#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems wrong for emotion and mui to be at this top level.
And the react types.
</blockquote></details>

Done.
___
*[`components/language-picker/README.md` line 3 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lQWJb0aziiYyjCJfe:-O4lcZRnCVjwSSDfIoQd:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/README.md#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Typically if we refer to it in prose, it is the Bloom Editor. Or it can be the repo: BloomDesktop. Maybe worth a link to the repo?
</blockquote></details>

Done.
___
*[`components/language-picker/README.md` line 28 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lR353-cYodzTKM8wz:-O4lcnBa-2mEqruojhN6:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/README.md#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's be consistent with capitalization of "Nx".
I suggest lowercase everywhere.
</blockquote></details>

Done.
___
*[`components/language-picker/README.md` line 40 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lRNtF9NieJ41iTp0T:-O4lcrXy9Um28hyOiOVU:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/README.md#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Extra period.
</blockquote></details>

Done.
___
*[`components/language-picker/common/find-language/package.json` line 37 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/3#-O4lQDJ87FsMtTG8K5ag:-O4lSD6iBV2BRqv_rLke:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/667ba5fdd39983449d658ac71bded962a516154b/components/language-picker/common/find-language/package.json#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why does this package need react stuff?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Comment by imnasnainaec** [comment]
> > ```
> > First, set up Nx if you haven't done so already (see [README.md](../../README.md)).
> > 
> > We recommend installing nx globally, but if you haven't, you can just prefix all the commands with `npx`
> > ```
> 
> Let's be consistent with capitalization of "Nx". I suggest lowercase everywhere.

FWIW, they refer to their own product with capitalized Nx.

**Comment by andrew-polk** [comment]
> > Let's be consistent with capitalization of "Nx". I suggest lowercase everywhere.
> 
> FWIW, they refer to their own product with capitalized Nx.

Thanks. At first, I was leaning toward using Nx for the thing and nx for the commands, but after seeing it would sometimes be ambiguous, I thought it was easier to just use nx everywhere.
Example: "... you can alternatively run the nx commands ..."

**Pull request merged**
