### PR TITLE
config and cleanup

### PR DESCRIPTION
**Pull request by nabalone**
- switch the hook package to vite and make it publishable
- cleanup npm scripts
- tweaks to readmes

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/27)

### CODE REVIEW

**Comment by nabalone** [comment]
Ready for review, but please let me merge it myself as I will need to make a manual initial publish of the hook and then see if github actions works after that

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/27)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`image.png` line 0 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/27#-OAU65Bn5w87PJsFQkAa:-OAU65Bn5w87PJsFQkAb:bupcm7t) ([raw file](https://github.com/sillsdev/EthnoLib/blob/462aae178863b8d75cd82190e7d291afe34f8f83/image.png#L0)):*
Maybe worth giving this a different name?
How about readme-package-diagram.png?
___
*[`.vscode/settings.json` line 19 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/27#-OAU6MwEBVvKWy1u-oZF:-OAU6MwEBVvKWy1u-oZG:b7lo419) ([raw file](https://github.com/sillsdev/EthnoLib/blob/462aae178863b8d75cd82190e7d291afe34f8f83/.vscode/settings.json#L19)):*
> ```JSON
>         "Subtag",
>         "subtags",
>         "tsup",
> ```

didn't you just get rid of tsup?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/27)* status: 6 of 16 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`.vscode/settings.json` line 19 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/27#-OAU6MwEBVvKWy1u-oZF:-OAU9w0V3P-Q-1x7N8M9:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/462aae178863b8d75cd82190e7d291afe34f8f83/.vscode/settings.json#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

didn't you just get rid of tsup?
</blockquote></details>

Done.
___
*[`image.png` line  at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/27#-OAU65Bn5w87PJsFQkAa:-OAU9utc5kdVvOfjg3Uq:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/462aae178863b8d75cd82190e7d291afe34f8f83/image.png#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe worth giving this a different name?
How about readme-package-diagram.png?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/27)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
