### PR TITLE
MUI theming colors

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/39)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/39)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx` line 191 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/39#-ODhYtB54OlFViJBWp9O:-ODhYtB54OlFViJBWp9P:b5j5a0x) ([raw file](https://github.com/sillsdev/EthnoLib/blob/166f19d6c5707937ea25e6d49836b621d8f4fe77/components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx#L191)):*
> ```XML
>       },
>     },
>   });
> ```

Pending changes we discussed:
- allowing the theme to set lighter and lightest
- README update
- comments on the override props

looks good

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/39)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx` line 191 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/39#-ODhYtB54OlFViJBWp9O:-ODh_pvH2xOhfjkOdWUS:b-oges1h) ([raw file](https://github.com/sillsdev/EthnoLib/blob/166f19d6c5707937ea25e6d49836b621d8f4fe77/components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx#L191)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Pending changes we discussed:
- allowing the theme to set lighter and lightest
- README update
- comments on the override props

looks good
</blockquote></details>

Sorry, I can't remember, what was I supposed to do for comments on the override props?

Also, during our meeting I had forgotten that I had made the languageCardBackgroundColorOverride  and scriptCardBackgroundColorOverride props at all. So now there are two ways of overriding the background colors; I updated the readme.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/39)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx` line 191 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/39#-ODhYtB54OlFViJBWp9O:-ODhcPHR9EaWQ1zLjzFf:b-icwalh) ([raw file](https://github.com/sillsdev/EthnoLib/blob/166f19d6c5707937ea25e6d49836b621d8f4fe77/components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx#L191)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Sorry, I can't remember, what was I supposed to do for comments on the override props?

Also, during our meeting I had forgotten that I had made the languageCardBackgroundColorOverride  and scriptCardBackgroundColorOverride props at all. So now there are two ways of overriding the background colors; I updated the readme.
</blockquote></details>

Sorry; we didn't actually talk about that one.
But it is probably worth updating the comment on each prop 
(which currently states "// if not provided, will use lighten(primaryColor, 0.7)")
to include that it will first use the theme's lighter and lightest if set.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/39)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
