### PR TITLE
fix: prioritize whole word matches then prefix matches

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/34)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/34)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBffbzy-4aHYxXkP6VX:-OBffbzy-4aHYxXkP6VY:bjb09yv) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5a17aab64f49ede9780c78ba6ab610747c63031e/components/language-chooser/common/find-language/searchForLanguage.ts#L71)):*
> ```XML
>   const alreadyIncludedResultCodes = new Set();
>   for (const resultList of [
>     wholeWordMatchResults,
> ```

I feel like it would be less clean though more efficient to do 
```
const results = [...wholeWordMatchResults]
const alreadyIncludedResultCodes = new Set([...wholeWordMatchResults.map(r => r.item.iso639_3_code)]);
for (const resultList of prefixMatchResults, fuzzyMatchResults)
{...}
```

Which do you think is better?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/34)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBffbzy-4aHYxXkP6VX:-OBfu3LG7NQepg7dgkis:b-q255al) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5a17aab64f49ede9780c78ba6ab610747c63031e/components/language-chooser/common/find-language/searchForLanguage.ts#L71)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I feel like it would be less clean though more efficient to do 
```
const results = [...wholeWordMatchResults]
const alreadyIncludedResultCodes = new Set([...wholeWordMatchResults.map(r => r.item.iso639_3_code)]);
for (const resultList of prefixMatchResults, fuzzyMatchResults)
{...}
```

Which do you think is better?
</blockquote></details>

an AI claims this will preserve original order:
```
  // Combine the three lists in order
  const combinedList = [...list1, ...list2, ...list3];
  
  // Remove duplicates while preserving order
  const uniqueSet = new Set(combinedList);
  
  // Convert Set back to array
  return Array.from(uniqueSet);
```

That will work, right?
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBfs4tCDwwjqPNDibIB:-OBfs4tCDwwjqPNDibIC:b-bm1xpt) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5514df00d5dc72aecdb66ac9b388416c1cd041a2/components/language-chooser/common/find-language/searchForLanguage.ts#L9)):*
> ```XML
> }
> 
> // We will then also pad the search terms with spaces and so be able to detect an exact whole-word match or prefix match
> ```

I don't understand this comment. It states, "We will then also." But there is no context for "then" or "also".
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 88 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBfureK2-3NU5n035v6:-OBfureK2-3NU5n035v7:bdy2btt) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5514df00d5dc72aecdb66ac9b388416c1cd041a2/components/language-chooser/common/find-language/searchForLanguage.ts#L88)):*
> ```XML
>   }
> 
>   return results.map((result) => ({
> ```

Probably worth a comment about how we have to remove the spaces we added to do the exact match.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/34)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBffbzy-4aHYxXkP6VX:-OBkifvS2q_Dryftf-Y9:b-e5q0uc) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5a17aab64f49ede9780c78ba6ab610747c63031e/components/language-chooser/common/find-language/searchForLanguage.ts#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

an AI claims this will preserve original order:
```
  // Combine the three lists in order
  const combinedList = [...list1, ...list2, ...list3];
  
  // Remove duplicates while preserving order
  const uniqueSet = new Set(combinedList);
  
  // Convert Set back to array
  return Array.from(uniqueSet);
```

That will work, right?
</blockquote></details>

The result items are not identical even for the same language, and I think Set() uses reference equality anyway? In order to make that work I believe we would need to make a set with a custom equality function, which looks more messy than it would be worth? Currently I'm just making a set of their iso 639-3 codes. 
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 9 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBfs4tCDwwjqPNDibIB:-OBkifJf1xpCnbSlLwx8:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5514df00d5dc72aecdb66ac9b388416c1cd041a2/components/language-chooser/common/find-language/searchForLanguage.ts#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't understand this comment. It states, "We will then also." But there is no context for "then" or "also".
</blockquote></details>

Done.
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 88 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBfureK2-3NU5n035v6:-OBklp7Z89sGC4Q5ZJl1:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5514df00d5dc72aecdb66ac9b388416c1cd041a2/components/language-chooser/common/find-language/searchForLanguage.ts#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably worth a comment about how we have to remove the spaces we added to do the exact match.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/34)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 71 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBffbzy-4aHYxXkP6VX:-OC-MnzW8YU6psqdJZiO:b1azv1c) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5a17aab64f49ede9780c78ba6ab610747c63031e/components/language-chooser/common/find-language/searchForLanguage.ts#L71)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

The result items are not identical even for the same language, and I think Set() uses reference equality anyway? In order to make that work I believe we would need to make a set with a custom equality function, which looks more messy than it would be worth? Currently I'm just making a set of their iso 639-3 codes.
</blockquote></details>

Oops. Good point.
Let's go for readability unless we start to see a reason to enhance for performance.
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 88 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/34#-OBfureK2-3NU5n035v6:-OC-LReVBoAtGEV2aNuC:b-gg1z3v) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5514df00d5dc72aecdb66ac9b388416c1cd041a2/components/language-chooser/common/find-language/searchForLanguage.ts#L88)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Either this got missed or I miscommunicated.
I'm suggesting we add a comment here explaining why we are trimming.
Something like
// We trim off the spaces that we used above to find exact and prefix matches.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
