### PR TITLE
fix: prioritize prefix matches but still find late in string matches

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/19)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/19)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 46 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/19#-O8w_1l65AysErLA0g5I:-O8w_1l65AysErLA0g5J:b-buar41) ([raw file](https://github.com/sillsdev/EthnoLib/blob/ad3ae525b58206a12b2ff20d29ebea89b8f99df8/components/language-chooser/common/find-language/searchForLanguage.ts#L46)):*
> ```XML
>   const prefixOnlyResults = prefixOnlyFuse.search(queryString);
> 
>   const locationIndependentFuse = new Fuse(languages as ILanguage[], {
> ```

I got tripped up by the term location for a while thinking it had something to do with region as opposed to the location within the string.
Would it be helpful to rename `locationIndepdendentResults` to `allFuzzyMatchResults` or something similar? Possibly just `fuzzyResults`? Or even `allResults`?

**Comment by nabalone** [comment]
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 46 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/19#-O8w_1l65AysErLA0g5I:-O8wwZFyD_lJvfTsLKPN:b-jlkyca) ([raw file](https://github.com/sillsdev/EthnoLib/blob/ad3ae525b58206a12b2ff20d29ebea89b8f99df8/components/language-chooser/common/find-language/searchForLanguage.ts#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I got tripped up by the term location for a while thinking it had something to do with region as opposed to the location within the string.
Would it be helpful to rename `locationIndepdendentResults` to `allFuzzyMatchResults` or something similar? Possibly just `fuzzyResults`? Or even `allResults`?
</blockquote></details>

Done. Makes sense, I didn't thank of that!

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/19)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 46 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/19#-O8w_1l65AysErLA0g5I:-O8wxjcw-gGcqXh8U_mC:b-d09zjp) ([raw file](https://github.com/sillsdev/EthnoLib/blob/ad3ae525b58206a12b2ff20d29ebea89b8f99df8/components/language-chooser/common/find-language/searchForLanguage.ts#L46)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done. Makes sense, I didn't thank of that!
</blockquote></details>

One more place to change it (in the comment).
Then feel free to merge.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/19)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 46 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/19#-O8w_1l65AysErLA0g5I:-O8xH1WQ58PCOcyz1pzk:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/ad3ae525b58206a12b2ff20d29ebea89b8f99df8/components/language-chooser/common/find-language/searchForLanguage.ts#L46)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

One more place to change it (in the comment).
Then feel free to merge.
</blockquote></details>

Done.

**Pull request merged**
