### PR TITLE
fix: dialog buttons and header should not be baked into the component

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)

### CODE REVIEW

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts` line 234 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OC9kJBHAneTGKIuYFkD:-OC9kJBHAneTGKIuYFkE:b-sdtkv8) ([raw file](https://github.com/sillsdev/EthnoLib/blob/a3fcd688fe2b95384c05b4ce663729a72ccd3c54/components/language-chooser/react/common/language-chooser-react-hook/useLanguageChooser.ts#L234)):*
> ```XML
> 
> export function defaultDisplayName(language: ILanguage) {
>   return stripDemarcation(language.autonym || language.exonym || "");
> ```

exonym is always a string so not sure why I had this

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx` line 135 at r3](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OCACrA37ojcidiOCfah:-OCACrA37ojcidiOCfai:baqrkdf) ([raw file](https://github.com/sillsdev/EthnoLib/blob/aa104ec83ee1b4d8153900d725c802ac36ef822f/components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx#L135)):*
> ```XML
>       }
>     }
>   }, [lp.selectedLanguage, lp.selectedScript, lp.customizableLanguageDetails]);
> ```

Were you going to add props.onSelectionChange?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx` line 135 at r3](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OCACrA37ojcidiOCfah:-OCAPsWF2i3N2fQExIpb:b-b005lp) ([raw file](https://github.com/sillsdev/EthnoLib/blob/aa104ec83ee1b4d8153900d725c802ac36ef822f/components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Were you going to add props.onSelectionChange?
</blockquote></details>

Hmm, I am trying it and running into a problem of infinite re-renders, I think because props.onSelectionChange gets redefined. It stops if I throw a useCallback on props.onSelectionChange, but that defeats the purpose of putting it in the dependencies list.

Thinking more about it, I think the current behavior is reasonable enough - we call onSelectionChange whenever the selection is changed. If you want it to be called for the initial round of automatic selection making, it needs to exist at that time. What do you think?
___
*[`components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx` line 105 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OC9qZIxEolN4uMeA3OT:-OCAPtSQ6UNuurX5Psvs:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5168a3db3da77d8c310f58345f6bbdd856658657/components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx#L105)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This should probably have a different ID so we don't confuse it with the lang chooser itself.
I'm not sure what is best.
`lang-chooser-dialog-content`?
`lang-chooser-wrapper`?
something else?
</blockquote></details>

Done.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx` line 105 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OC9qZIxEolN4uMeA3OT:-OCAS-bG8bn-KVEY6JPf:beoyt8y) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5168a3db3da77d8c310f58345f6bbdd856658657/components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx#L105)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Do we make a consistent practice of putting ids on everything? I've only been doing it because it makes it easier to use the browser Inspector when there are a lot of nested divs

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)* status: all files reviewed, 1 unresolved discussion

___
*[`components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx` line 135 at r3](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OCACrA37ojcidiOCfah:-OCAZLs5Bl2FxrSec5Ib:b-rxqkly) ([raw file](https://github.com/sillsdev/EthnoLib/blob/aa104ec83ee1b4d8153900d725c802ac36ef822f/components/language-chooser/react/language-chooser-react-mui/src/LanguageChooser.tsx#L135)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Hmm, I am trying it and running into a problem of infinite re-renders, I think because props.onSelectionChange gets redefined. It stops if I throw a useCallback on props.onSelectionChange, but that defeats the purpose of putting it in the dependencies list.

Thinking more about it, I think the current behavior is reasonable enough - we call onSelectionChange whenever the selection is changed. If you want it to be called for the initial round of automatic selection making, it needs to exist at that time. What do you think?
</blockquote></details>

Sounds good. Sorry to send you on a goose chase.
___
*[`components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx` line 105 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/36#-OC9qZIxEolN4uMeA3OT:-OCAZCi3661UX6DT6cjz:b-wuey9n) ([raw file](https://github.com/sillsdev/EthnoLib/blob/5168a3db3da77d8c310f58345f6bbdd856658657/components/language-chooser/react/language-chooser-react-mui/src/demos/LanguageChooserDialog.tsx#L105)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Do we make a consistent practice of putting ids on everything? I've only been doing it because it makes it easier to use the browser Inspector when there are a lot of nested divs
</blockquote></details>

I don't think we've done it typically, no.

**Review by andrew-polk — APPROVED** [review]
> Dismissed @nabalone from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
