### PR TITLE
autonym fallback to "localname" if no "localnames" field

### PR DESCRIPTION
**Pull request by nabalone**
Addresses https://github.com/sillsdev/EthnoLib/issues/40

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/42)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/42)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/langtagProcessing.ts` line 110 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/42#-ODN2ghoATnd0THPHjm2:-ODN2ghoATnd0THPHjm3:b-i7ofxk) ([raw file](https://github.com/sillsdev/EthnoLib/blob/8519781eece9ae195b5fd9daedc4413511d677ba/components/language-chooser/common/find-language/langtagProcessing.ts#L110)):*
> ```XML
>       langs[entry.iso639_3].localnames0 || entry.localnames?.[0];
>     langs[entry.iso639_3].localname =
>       langs[entry.iso639_3].localname || entry.localname;
> ```

I'm probably just missing something, but it seems like it would simplify things to 
1. let the data structure continue to just have autonym
2. use the logic here of falling back to localname if there is no localnames

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/42)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/deletable.json` line 0 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/42#-ODNSh1S9KeyGc-nQxor:-ODNSh1S9KeyGc-nQxos:bxngezm) ([raw file](https://github.com/sillsdev/EthnoLib/blob/534e5d76c61d254b1e4b751e2485d468a59d825f/components/language-chooser/common/find-language/deletable.json#L0)):*
Was adding this file an accident?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/42)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`components/language-chooser/common/find-language/deletable.json` line  at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/42#-ODNSh1S9KeyGc-nQxor:-ODgW_rN7qP6RcUvWErk:b6ef043) ([raw file](https://github.com/sillsdev/EthnoLib/blob/534e5d76c61d254b1e4b751e2485d468a59d825f/components/language-chooser/common/find-language/deletable.json#L)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was adding this file an accident?
</blockquote></details>

Oops yes sorry. Deleted.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/42)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
