### PR TITLE
fix: langtag bug fix and region lookup

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/38)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/38)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @nabalone)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 75 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKqohr6lwd_IcQ1u8O:-OCKqohr6lwd_IcQ1u8P:b-2oeo50) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/common/find-language/searchForLanguage.ts#L75)):*
> ```XML
>   const resultsByIso639_3Code = new Map<string, FuseResult<ILanguage>>();
>   for (const result of fuzzyMatchResults) {
>     resultsByIso639_3Code.set(result.item.iso639_3_code, result);
> ```

Is it guaranteed that no two items in fuzzyMatchResults have the same iso639? For example, searching for "en", you might get one match because it's an exact match for the lang code, one because it's a prefix of England (country), and one because it's a prefix of 'English' (language).
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 82 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKoHx01Pcv8SZgvmh9:-OCKoHx01Pcv8SZgvmhA:b-6v7rwg) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/common/find-language/searchForLanguage.ts#L82)):*
> ```XML
>       const isoCode = r.item.iso639_3_code;
>       const correctResult = resultsByIso639_3Code.get(isoCode);
>       if (correctResult) {
> ```

Is it actually possible that correctResult is falsy? That is, that a result shows up in one of the other lists but NOT in the fuzzy match? If so, would we want to throw or include the result despite an incorrect match index?
Or maybe, falsy just means that it's in both wholeWordMatchResults and prefixMatchResults, and you don't want to add it twice?
That makes sense because prefixMatchResults will have ALL the items from wholeWordMatchResults. A comment might be helpful.
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 88 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKotF69iV3XBFG5TQM:-OCKotF69iV3XBFG5TQN:b-v6q9xw) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/common/find-language/searchForLanguage.ts#L88)):*
> ```XML
>     }
>   }
>   orderedResults.push(...resultsByIso639_3Code.values());
> ```

Is there any usefulness to the order of fuzzyMatchResults? Because this will randomize the ones that weren't in the other lists.
(You could just make fuzzyMatchResults a third item in the list above if it's worth keeping the order.)
___
*[`components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts` line 139 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKnHK48srJG138ciui:-OCKnHK48srJG138ciuj:b8g6d6k) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts#L139)):*
> ```XML
>     getMaximalLangtag(`${languageSubtag}`) ||
>     "";
>   const maximalTagOrthography = parseLangtagFromLangChooser(maximalTag || "");
> ```

Don't need to OR in empty string again.
___
*[`components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts` line 144 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKmnTs5FjqegufZm6X:-OCKmnTs5FjqegufZm6Y:bybs5nd) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts#L144)):*
> ```XML
>     expect(defaultRegionForLangTag("en-Latn-CN")?.name).toEqual("China");
>     expect(defaultRegionForLangTag("en-CN-x-foobar")?.name).toEqual("China");
>     expect(defaultRegionForLangTag("en-CN")?.name).toEqual("China");
> ```

Probably good to test at least one that has a different region tag, especially one that doesn't need special conversion. (Or maybe they all get expanded?)
___
*[`components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts` line 146 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKmxXPCjQLQ0J96QAZ:-OCKmxXPCjQLQ0J96QA_:b9i9gt9) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts#L146)):*
> ```XML
>     expect(defaultRegionForLangTag("en-CN")?.name).toEqual("China");
>   });
>   it("should return the region for the closest maximal equivalent of the langauge tag", () => {
> ```

language



_Code quote:_
```XML
langauge
```

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/38)* status: all files reviewed, 6 unresolved discussions (waiting on @nabalone)

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/38)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 75 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKqohr6lwd_IcQ1u8O:-OCKvPJN6tOglI9XPmRG:b-39awpq) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/common/find-language/searchForLanguage.ts#L75)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it guaranteed that no two items in fuzzyMatchResults have the same iso639? For example, searching for "en", you might get one match because it's an exact match for the lang code, one because it's a prefix of England (country), and one because it's a prefix of 'English' (language).
</blockquote></details>

Yes it is guaranteed. At this point we have already merged all entries with the same iso639 code
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 82 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKoHx01Pcv8SZgvmh9:-OCKvVP3082WkxuUsTWe:bd9s2kk) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/common/find-language/searchForLanguage.ts#L82)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it actually possible that correctResult is falsy? That is, that a result shows up in one of the other lists but NOT in the fuzzy match? If so, would we want to throw or include the result despite an incorrect match index?
Or maybe, falsy just means that it's in both wholeWordMatchResults and prefixMatchResults, and you don't want to add it twice?
That makes sense because prefixMatchResults will have ALL the items from wholeWordMatchResults. A comment might be helpful.
</blockquote></details>

Done. Yes, falsy if it was already added
___
*[`components/language-chooser/common/find-language/searchForLanguage.ts` line 88 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKotF69iV3XBFG5TQM:-OCKx9B-4BWMIbDtbO_h:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/common/find-language/searchForLanguage.ts#L88)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there any usefulness to the order of fuzzyMatchResults? Because this will randomize the ones that weren't in the other lists.
(You could just make fuzzyMatchResults a third item in the list above if it's worth keeping the order.)
</blockquote></details>

Done.
___
*[`components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts` line 139 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKnHK48srJG138ciui:-OCKxS2xDr5QcXHRz1Zp:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.ts#L139)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Don't need to OR in empty string again.
</blockquote></details>

Done.
___
*[`components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts` line 144 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKmnTs5FjqegufZm6X:-OCKxqQg88t55AWvagGd:b-260wdv) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts#L144)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably good to test at least one that has a different region tag, especially one that doesn't need special conversion. (Or maybe they all get expanded?)
</blockquote></details>

Done.  If I am understanding correctly, they do all get expanded
___
*[`components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts` line 146 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/38#-OCKmxXPCjQLQ0J96QAZ:-OCKy5mi0KwfMFpjzJ7Z:b-896fix) ([raw file](https://github.com/sillsdev/EthnoLib/blob/71e07e25604a04d8bf1d5748c42cfa14b64be06a/components/language-chooser/react/common/language-chooser-react-hook/languageTagHandling.spec.ts#L146)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

language
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
