### PR TITLE
Configuration, reorganization, and fixes

### PR DESCRIPTION
**Pull request by nabalone**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)

### CODE REVIEW

**Comment by nabalone** [comment]
Before merging we will need to change the trigger branch to `main` in `release.yml`

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 76 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`package.json` line 35 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8D6Q-Z-v_IHELSmB1o:-O8D6Q-Z-v_IHELSmB1p:b-z97xw3) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/package.json#L35)):*
> ```JSON
>   },
>   "dependencies": {
>     "@storybook/test-runner": "^0.19.1"
> ```

I'm guessing this is needed so we can publish to git?
It seems strange to have part of storybook as part of dependencies.
___
*[`components/language-chooser/common/find-language/vitest.config.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8DAxTB9_Qyo5PGyxrK:-O8DAxTB9_Qyo5PGyxrL:baau4gx) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/components/language-chooser/common/find-language/vitest.config.ts#L9)):*
> ```XML
>   //     requireAssertions: true,
>   //   },
>   // },
> ```

I thought we had decided we wanted this check.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`package.json` line 35 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8D6Q-Z-v_IHELSmB1o:-O8MtOE32rnngQW_rj8k:bmdcivq) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/package.json#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm guessing this is needed so we can publish to git?
It seems strange to have part of storybook as part of dependencies.
</blockquote></details>

Moved it to dev dependencies
___
*[`components/language-chooser/common/find-language/vitest.config.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8DAxTB9_Qyo5PGyxrK:-O8MtcDKEku3a-cOhovv:b-7a75pp) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/components/language-chooser/common/find-language/vitest.config.ts#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought we had decided we wanted this check.
</blockquote></details>

the requireAssertions check is introduced in vitest 2 and I downgraded to vitest 1, probably for compatibility. Not sure what to do now

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)* status: 73 of 76 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`components/language-chooser/common/find-language/vitest.config.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8DAxTB9_Qyo5PGyxrK:-O8N23tx6vQgOIB16dZI:b-gkz6qj) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/components/language-chooser/common/find-language/vitest.config.ts#L9)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

the requireAssertions check is introduced in vitest 2 and I downgraded to vitest 1, probably for compatibility. Not sure what to do now
</blockquote></details>

I will reevaluate whether we can use vitest 2

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`.prettierrc` line 2 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8N3CvA8nY25BjPVAe2:-O8N3CvA8nY25BjPVAe3:b-jraarb) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d814b6f4feeb12ce912fa4e039c9bfcb5712a531/.prettierrc#L2)):*
> ```
> {
>   "singleQuote": false
> ```

When this got changed to true, I saw a bunch of things got changed to use single quotes. But now it with it going back to double, I don't see the corresponding changes being reverted.
Probably if we save one of those files now, we will get spurious changes?

I'm not sure what is worth doing about it now...
Maybe worth a quick chat about why this got switched back and forth?
___
*[`components/language-chooser/common/find-language/vitest.config.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8DAxTB9_Qyo5PGyxrK:-O8N24ZN7-77gV6QIITV:bt23q0b) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/components/language-chooser/common/find-language/vitest.config.ts#L9)):*
> I will reevaluate whether we can use vitest 2

That's worth a short experiment.
Else, just comment that we want this check but currently we have vitest1 which doesn't support it.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)* status: 65 of 76 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`components/language-chooser/common/find-language/vitest.config.ts` line 9 at r1](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8DAxTB9_Qyo5PGyxrK:-O8NwJ228k-W4jh1WLjP:b-bttoee) ([raw file](https://github.com/sillsdev/EthnoLib/blob/15c4a257e1e799b6fd05cb045fa09251a196be3d/components/language-chooser/common/find-language/vitest.config.ts#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> I will reevaluate whether we can use vitest 2

That's worth a short experiment.
Else, just comment that we want this check but currently we have vitest1 which doesn't support it.
</blockquote></details>

Added comment
___
*[`.prettierrc` line 2 at r2](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-O8N3CvA8nY25BjPVAe2:-O8NwOZ9ANVJfdItDwLA:b-hh0tpn) ([raw file](https://github.com/sillsdev/EthnoLib/blob/d814b6f4feeb12ce912fa4e039c9bfcb5712a531/.prettierrc#L2)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

When this got changed to true, I saw a bunch of things got changed to use single quotes. But now it with it going back to double, I don't see the corresponding changes being reverted.
Probably if we save one of those files now, we will get spurious changes?

I'm not sure what is worth doing about it now...
Maybe worth a quick chat about why this got switched back and forth?
</blockquote></details>

Should be fixed now

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Comment by nabalone** [comment]
I'm guessing we want to squash and merge this, and then I may need to manually move tags to allow the github actions to detect version and publish properly

**Review by andrew-polk — APPROVED** [review]
Looks ready to me. Yes, squash looks best.
I'll let you handle the merge, etc.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/EthnoLib/9#-:-O8Nx5sc49l_MqVFlupf:b-tjb3l6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
